---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-gitsource-pvc
spec:
  accessModes: {{ .Values.persistence.accessModes | default (list "ReadWriteOnce") }}
  resources:
    requests:
      storage: 1Gi
