apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnc-ingress
  annotations:
    cert-manager.io/issuer: {{ include "opnc.issuerName" . }}
    {{ if eq .Values.ingress.ingressClassName "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{ end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "traefik" }}
  tls:
    - hosts:
        - {{ include "opnc.openprojectHost" . }}
        - {{ include "opnc.nextcloudHost" . }}
        - {{ include "opnc.keycloakHost" . }}
        {{ if .Values.openproject.localSourcePath }}
        - {{ include "opnc.openprojectAssetHost" . }}
        {{ end }}
      secretName: {{ include "opnc.tlsSecretName" . }}
  rules:
    - host: {{ include "opnc.openprojectHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openproject
                port:
                  number: 8080

    {{ if .Values.openproject.localSourcePath }}
    - host: {{ include "opnc.openprojectAssetHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: op-assets-svc
                port:
                  number: 4200
    {{ end }}

    - host: {{ include "opnc.nextcloudHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
    - host: {{ include "opnc.keycloakHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
